package com.example.ui.theme

object Translator {
    private val translations = mapOf(
        "ar" to mapOf(
            "home" to "الرئيسية",
            "sections" to "الأقسام",
            "transactions" to "المعاملات",
            "statistics" to "الإحصائيات",
            "dashboard" to "لوحة الأرباح 📈",
            "debts" to "الديون",
            "settings" to "الإعدادات ⚙️",
            "app_title" to "ورشـتـي - تسيير المحل الـذكي",
            "total_cost" to "تكلفة المشتريات والمصاريف",
            "total_revenue" to "المداخيل الإجمالية",
            "total_profit" to "الأرباح الصافية للورشة",
            "active_credit" to "كريدي الزبائن غير المسترد",
            "add_transaction" to "إضافة عملية صيانة/مبيعات ➕",
            "no_transactions" to "لا توجد عمليات مسجلة في هذه الفترة.",
            "search_placeholder" to "بحث باسم الزبون، العطل أو الهاتف...",
            "all" to "الكل",
            "today" to "اليوم",
            "week" to "هذا الأسبوع",
            "month" to "هذا الشهر",
            "customer_debts" to "قائمة كريدي الزبائن",
            "personal_debts" to "الديون الشخصية والموردين",
            "owed_to_me" to "نسالهم (أطالبهم بأموال)",
            "owed_by_me" to "يسالوني (يطالبونني بأموال)",
            "add_debt" to "تسجيل دين جديد ➕",
            "category" to "الفئة",
            "phone_model" to "موديل الجهاز",
            "customer" to "الزبون",
            "phone_num" to "رقم الهاتف",
            "cost_price" to "سعر الشراء / التكلفة (د.ج)",
            "sale_price" to "سعر البيع / الثمن (د.ج)",
            "credit_total" to "الحساب كريدي؟",
            "notes" to "ملاحظات إضافية",
            "save" to "حفظ البيانات",
            "cancel" to "إلغاء",
            "payment_received" to "المبلغ المدفوع (العربون)",
            "credit_remaining" to "المتبقي كريدي",
            "date" to "التاريخ",
            "profit" to "الربح",
            "action" to "العمليات",
            "edit" to "تعديل",
            "delete" to "حذف",
            "clear_all" to "تفريغ السجل الكامل",
            "confirm_clear" to "هل أنت متأكد من مسح جميع البيانات بشكل نهائي؟",
            "sample_data" to "ملء بيانات تجريبية",
            "status_unpaid" to "غير مسدد 🔴",
            "status_paid" to "تم التسديد 🟢",
            "google_assistant" to "مساعد جوجل الذكي للورشة ✨",
            "settings_theme" to "سمة وتصميم التطبيق",
            "settings_language" to "لغة التطبيق والتعريب",
            "settings_backup" to "النسخ السحابي والملفات",
            "settings_export_excel" to "تصدير الداتا كملف Excel (CSV) 📊",
            "settings_import_excel" to "استيراد واسترجاع الداتا من ملف 📥",
            "settings_sync_drive" to "مزامنة Google Drive السحابية ☁️",
            "theme_emerald" to "الزمرد الكلاسيكي 💚",
            "theme_ocean" to "شواطئ المحيط 💙",
            "theme_amber" to "الذهبي الملكي 💛",
            "theme_purple" to "البنفسجي الإبداعي 💜",
            "theme_slate" to "الرمادي الفولاذي 🩶",
            "theme_liquid_glass" to "زجاجي سائل 🌊",
            "lang_ar" to "العربية 🇩🇿",
            "lang_fr" to "Français 🇫🇷",
            "lang_en" to "English 🇬🇧",
            "drive_status" to "اتصال مساحة Google Drive",
            "drive_connected" to "نشط ومزامن تلقائياً (عبر ميزات النظام) ✅",
            "drive_info_desc" to "ميزة النسخ الاحتياطي تستخدم مستكشف ملفات نظام أندرويد السحابي. بمجرد اختيار الحفظ أو الاسترجاع، ستتمكن من التحديد مباشرة من مجلد Google Drive الخاص بك بطريقة آمنة ومتكاملة 100%.",
            "backup_success" to "تم تصدير نسخة البيانات بنجاح!",
            "restore_success" to "تم استيراد نسخة البيانات بنجاح!",
            "restore_error" to "خطأ في قراءة ملف نسخة البيانات. يرجى التحقق من صياغته.",
            "import_count" to "تم إضافة %d عمليات و %d ديون!",
            "delete_app_data" to "حذف جميع بيانات التطبيق ⚠️",
            "delete_app_data_desc" to "سيتم مسح جميع عمليات الصيانة والديون والاستثمارات والمصاريف بشكل نهائي ولا يمكن استعادتها.",
            "delete_confirm_title" to "هل أنت متأكد تماماً؟",
            "delete_success_msg" to "تم حذف جميع بيانات التطبيق بنجاح"
        ),
        "fr" to mapOf(
            "home" to "Accueil",
            "sections" to "Rayons",
            "transactions" to "Transactions",
            "statistics" to "Stats",
            "dashboard" to "Tableau de Bord 📈",
            "debts" to "Dettes",
            "settings" to "Paramètres ⚙️",
            "app_title" to "Warshati - Gestion d'Atelier",
            "total_cost" to "Coût Total des Achats & Dépenses",
            "total_revenue" to "Revenus Globaux Brut",
            "total_profit" to "Bénéfice Net d'Atelier",
            "active_credit" to "Crédits Clients Actifs",
            "add_transaction" to "Nouvelle Réparation / Vente ➕",
            "no_transactions" to "Aucune transaction enregistrée.",
            "search_placeholder" to "Client, panne, appareil...",
            "all" to "Tous",
            "today" to "Aujourd'hui",
            "week" to "Cette Semaine",
            "month" to "Ce Mois-ci",
            "customer_debts" to "Liste des Crédits Clients",
            "personal_debts" to "Dettes Personnelles & Fournisseurs",
            "owed_to_me" to "À recevoir (Je réclame)",
            "owed_by_me" to "À payer (On me réclame)",
            "add_debt" to "Ajouter une Dette ➕",
            "category" to "Catégorie",
            "phone_model" to "Modèle d'appareil",
            "customer" to "Client",
            "phone_num" to "Numéro de téléphone",
            "cost_price" to "Coût d'achat de la pièce",
            "sale_price" to "Prix de vente ou réparation",
            "credit_total" to "Vendu à crédit ?",
            "notes" to "Remarques / Notes",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "payment_received" to "Montant Payé (Acompte)",
            "credit_remaining" to "Reste à payer",
            "date" to "Date",
            "profit" to "Bénéfice",
            "action" to "Actions",
            "edit" to "Modifier",
            "delete" to "Supprimer",
            "clear_all" to "Vider tout l'historique",
            "confirm_clear" to "Voulez-vous vraiment effacer définitivement vos données ?",
            "sample_data" to "Charger données d'essai",
            "status_unpaid" to "Non Payé 🔴",
            "status_paid" to "Payé 🟢",
            "google_assistant" to "Assistant IA Google Spark ✨",
            "settings_theme" to "Thème & Style Visuel",
            "settings_language" to "Langue de l'application",
            "settings_backup" to "Sauvegarde & Fichiers",
            "settings_export_excel" to "Exporter en Excel (CSV) 📊",
            "settings_import_excel" to "Importer depuis un fichier 📥",
            "settings_sync_drive" to "Mise à niveau Google Drive ☁️",
            "theme_emerald" to "Émeraude Classique 💚",
            "theme_ocean" to "Côtes de l'Océan 💙",
            "theme_amber" to "Or Royal Ambré 💛",
            "theme_purple" to "Violet Créatif 💜",
            "theme_slate" to "Gris Acier Moderne 🩶",
            "theme_liquid_glass" to "Verre Liquide 🌊",
            "lang_ar" to "العربية 🇩🇿",
            "lang_fr" to "Français 🇫🇷",
            "lang_en" to "English 🇬🇧",
            "drive_status" to "Statut d'intégration Google Drive",
            "drive_connected" to "Actif via l'explorateur système ✅",
            "drive_info_desc" to "La sauvegarde cloud utilise l'explorateur natif Android. En enregistrant ou en important, sélectionnez directement votre Google Drive de manière 100% sécurisée.",
            "backup_success" to "Exportation réussie !",
            "restore_success" to "Importation réussie avec succès !",
            "restore_error" to "Format de fichier invalide. Veuillez vérifier le fichier.",
            "import_count" to "%d transactions et %d dettes importées !",
            "delete_app_data" to "Supprimer toutes les données ⚠️",
            "delete_app_data_desc" to "Toutes les réparations, dettes, investissements et dépenses seront définitivement effacées et irrécupérables.",
            "delete_confirm_title" to "Êtes-vous absolument sûr ?",
            "delete_success_msg" to "Toutes les données de l'application ont été supprimées."
        ),
        "en" to mapOf(
            "home" to "Home",
            "sections" to "Sections",
            "transactions" to "Transactions",
            "statistics" to "Stats",
            "dashboard" to "Dashboard 📈",
            "debts" to "Debts",
            "settings" to "Settings ⚙️",
            "app_title" to "Warshati - Shop Management",
            "total_cost" to "Total Costs & Expenses",
            "total_revenue" to "Total Revenue",
            "total_profit" to "Net Shop Profit",
            "active_credit" to "Outstanding Customer Credits",
            "add_transaction" to "Add Maintenance / Sale ➕",
            "no_transactions" to "No transactions found.",
            "search_placeholder" to "Search client, fault, phone...",
            "all" to "All",
            "today" to "Today",
            "week" to "This Week",
            "month" to "This Month",
            "customer_debts" to "Customer Credits Ledger",
            "personal_debts" to "Personal & Vendor Debts",
            "owed_to_me" to "Owed to Me (Receivables)",
            "owed_by_me" to "Owed by Me (Payables)",
            "add_debt" to "Record New Debt ➕",
            "category" to "Category",
            "phone_model" to "Device Model",
            "customer" to "Customer Name",
            "phone_num" to "Phone Number",
            "cost_price" to "Part Cost / Expense",
            "sale_price" to "Selling / Repair Price",
            "credit_total" to "Is Credit Account?",
            "notes" to "Additional Notes",
            "save" to "Save Data",
            "cancel" to "Cancel",
            "payment_received" to "Amount Paid (Deposit)",
            "credit_remaining" to "Credit Balance",
            "date" to "Date",
            "profit" to "Profit",
            "action" to "Actions",
            "edit" to "Edit",
            "delete" to "Delete",
            "clear_all" to "Wipe Entire Ledger",
            "confirm_clear" to "Are you sure you want to permanently delete all shop logs?",
            "sample_data" to "Load Sample Data",
            "status_unpaid" to "Unpaid 🔴",
            "status_paid" to "Paid 🟢",
            "google_assistant" to "Google AI Smart Assistant ✨",
            "settings_theme" to "App Branding Colors",
            "settings_language" to "App Language Switcher",
            "settings_backup" to "Cloud Backups & Files",
            "settings_export_excel" to "Export Data to Excel (CSV) 📊",
            "settings_import_excel" to "Import Data from backup file 📥",
            "settings_sync_drive" to "Google Drive Cloud Engine ☁️",
            "theme_emerald" to "Classic Emerald Green 💚",
            "theme_ocean" to "Azure Blue Ocean 💙",
            "theme_amber" to "Royal Luxury Amber 💛",
            "theme_purple" to "Creative Deep Purple 💜",
            "theme_slate" to "Modern Steel Slate 🩶",
            "theme_liquid_glass" to "Liquid Glass 🌊",
            "lang_ar" to "العربية 🇩🇿",
            "lang_fr" to "Français 🇫🇷",
            "lang_en" to "English 🇬🇧",
            "drive_status" to "Google Drive Cloud Connection",
            "drive_connected" to "Active & secure (via Native Android Storage) ✅",
            "drive_info_desc" to "The cloud backup relies on Android's native storage integrations. When exporting or restoring, select your custom Google Drive directory safely.",
            "backup_success" to "Data backup exported cleanly!",
            "restore_success" to "Data backup imported successfully!",
            "restore_error" to "Invalid file format. Please check selected backup file.",
            "import_count" to "Imported %d transactions and %d debts!",
            "delete_app_data" to "Delete All App Data ⚠️",
            "delete_app_data_desc" to "This will permanently wipe all maintenance tasks, debts, investments, and expenses. This action cannot be undone.",
            "delete_confirm_title" to "Are you absolutely sure?",
            "delete_success_msg" to "All application data deleted successfully"
        )
    )

    fun translate(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["ar"]?.get(key) ?: key
    }
}
